
function Verb(infinitive, simple, participle, meaning)
{
	this.infinitive = infinitive;
	this.simple = simple;
	this.participle = participle;
	this.meaning = meaning;
}

function Round(min, max)
{
	this.roundVector = new Array();

	//max+1 because slice doesn't get the last index
	this.roundVector = verbBucket.slice(min, max+1);
}

verbBucket = new Array();

verbBucket.push(new Verb("ask","asked","asked","Say something in order to obtain an answer or some information"));
verbBucket.push(new Verb("awake","awoke","awoken","Stop sleeping"));
verbBucket.push(new Verb("be","was/were","been","Exist"));
verbBucket.push(new Verb("bear","bore","born","Carry/Support/Endure"));
verbBucket.push(new Verb("beat","beat","beaten","Strike/Defeat"));
verbBucket.push(new Verb("become","became","become","Begin to be"));
verbBucket.push(new Verb("begin","began","begun","Start"));
verbBucket.push(new Verb("believe","believed","believed","Accept (something) as true/Feel sure of the truth of"));
verbBucket.push(new Verb("bend","bent","bent","Shape or force (something straight) into a curve or angle/(of a person) incline the body downward from the vertical"));
verbBucket.push(new Verb("bet","bet","bet","Risk something, usually a sum of money, against someone else's on the basis of the outcome of a future event, such as the result of a race or game/Feel sure"));
verbBucket.push(new Verb("bid","bid","bid","Offer (a certain price) for something, especially at an auction"));
verbBucket.push(new Verb("bind","bound","bound","Tie or fasten (something) tightly/Cohere or cause to cohere in a single mass"));
verbBucket.push(new Verb("bite","bit","bitten","(of a person or animal) use the teeth to cut into something in order to eat it/(of a tool, tire, boot, etc.) grip a surface"));
verbBucket.push(new Verb("bleed","bled","bled","Lose blood from the body as a result of injury or illness"));
verbBucket.push(new Verb("blow","blew","blown","(of wind) move creating an air current/(of a person) expel air through pursed lips"));
verbBucket.push(new Verb("break","broke","broken","separate or cause to separate into pieces as a result of a blow, shock, or strain/interrupt (a continuity, sequence, or course)"));
verbBucket.push(new Verb("breed","bred","bred","Cause (an animal) to produce offspring, typically in a controlled and organized way"));
verbBucket.push(new Verb("bring","brought","brought","Come to a place with (someone or something)/cause (someone or something) to come to a place/make (someone or something) move in a particular direction or way"));
verbBucket.push(new Verb("broadcast","broadcast","broadcast","Transmit (a program or some information) by radio or television/scatter (seeds) by hand or machine rather than placing in drills or rows"));
verbBucket.push(new Verb("build","built","built","Construct (something, typically something large) by putting parts or material together over a period of time"));
verbBucket.push(new Verb("burn","burnt","burnt","(of a fire) flame or glow while consuming a material such as coal or wood/(of a person, the skin, or a part of the body) become red and painful through exposure to the sun"));
verbBucket.push(new Verb("burst","burst","burst","(of a container) break suddenly and violently apart, spilling the contents, typically as a result of an impact or internal pressure"));
verbBucket.push(new Verb("bust","bust","bust","To go bankrupt/to collapse from the strain of making a supreme effort"));
verbBucket.push(new Verb("buy","bought","bought","Obtain in exchange for payment"));
verbBucket.push(new Verb("call","called","called","Cry out to (someone) in order to summon them or attract their attention/Give (an infant or animal) a specified name"));
verbBucket.push(new Verb("cast","cast","cast","Throw (something) forcefully in a specified direction/Cause (light or shadow) to appear on a surface"));
verbBucket.push(new Verb("catch","caught","caught","Intercept and hold (something that has been thrown, propelled, or dropped)/Capture (a person or animal that tries or would try to escape)"));
verbBucket.push(new Verb("choose","chose","chosen","Pick out or select (someone or something) as being the best or most appropriate of two or more alternatives"));
verbBucket.push(new Verb("clap","clapped","clapped","Strike the palms of (one's hands) together repeatedly, typically in order to applaud"));
verbBucket.push(new Verb("cling","clung","clung","(of a person or animal) hold on tightly to"));
verbBucket.push(new Verb("come","came","come","Move or travel toward or into a place thought of as near or familiar to the speaker/Occur; happen; take place"));
verbBucket.push(new Verb("cost","cost","cost","(of an object or an action) require the payment of (a specified sum of money) before it can be acquired or done/Estimate the price of"));
verbBucket.push(new Verb("creep","crept","crept","Move slowly and carefully, especially in order to avoid being heard or noticed/(of an unwanted and negative characteristic or fact) occur or develop gradually and almost imperceptibly"));
verbBucket.push(new Verb("cut","cut","cut","Make an opening, incision, or wound in (something) with a sharp-edged tool or object/Remove (something) from something larger by using a sharp implement"));
verbBucket.push(new Verb("dare","dared","dared","Have the courage to do something/ Defy or challenge (someone) to do something"));
verbBucket.push(new Verb("deal","dealt","dealt","Distribute (cards) in an orderly rotation to the players for a game or round/ Take part in commercial trading of a particular commodity"));
verbBucket.push(new Verb("dig","dug","dug","Break up and move earth with a tool or machine, or with hands, paws, snout, etc/ Like, appreciate, or understand"));
verbBucket.push(new Verb("dive","dived","dived","Plunge head first into water/ (of an aircraft or bird) Plunge steeply downward through the air"));
verbBucket.push(new Verb("do","did","done","Perform (an action, the precise nature of which is often unspecified)/ Achieve or complete, in particular/ Used before a verb (except be, can, may, ought, shall, will ) in questions and negative statements/ Used to refer to a verb already mentioned"));
verbBucket.push(new Verb("draw","drew","drawn","Produce (a picture or diagram) by making lines and marks, especially with a pen or pencil, on paper/ Pull or drag (something such as a vehicle) so as to make it follow behind"));
verbBucket.push(new Verb("dream","dreamt","dreamt","Experience dreams during sleep/ Contemplate the possibility of doing something or that something might be the case"));
verbBucket.push(new Verb("drink","drank","drunk","Take (a liquid) into the mouth and swallow/ Watch or listen to something with eager pleasure or interest"));
verbBucket.push(new Verb("drive","drove","driven","Operate and control the direction and speed of a motor vehicle/ Propel or carry along by force in a specified direction"));
verbBucket.push(new Verb("eat","ate","eaten","Put (food) into the mouth and chew and swallow it"));
verbBucket.push(new Verb("fall","fell","fallen","Move downward, typically rapidly and freely without control, from a higher to a lower level/ (of a person) Lose one's balance and collapse"));
verbBucket.push(new Verb("feed","fed","fed","Give food to/ Supply (a machine) with material, power, or other things necessary for its operation"));
verbBucket.push(new Verb("feel","felt","felt","Be aware of (a person or object) through touching or being touched/ Experience (an emotion or sensation)"));
verbBucket.push(new Verb("fight","fought","fought","Take part in a violent struggle involving the exchange of physical blows or the use of weapons/ "));
verbBucket.push(new Verb("find","found","found","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("fit","fit","fit","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("flee","fled","fled","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("fling","flung","flung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("fly","flew","flown","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("forbid","forbade","forbidden","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("forecast","forecast","forecast","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("foresee","foresaw","foreseen","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("forget","forgot","forgotten","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("forgive","forgave","forgiven","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("forsake","forsook","forsaken","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("freeze","froze","frozen","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("get","got","got","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("give","gave","given","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("go","went","gone/been","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("grind","ground","ground","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("grow","grew","grown","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("handwrite","handwrote","handwritten","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("hang","hung","hung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("have","had","had","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("hear","heard","heard","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("help","helped","helped","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("hide","hid","hidden","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("hit","hit","hit","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("hold","held","held","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("hurt","hurt","hurt","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("inlay","inlaid","inlaid","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("input","input","input","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("keep","kept","kept","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("kneel","knelt","knelt","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("knit","knit","knit","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("know","knew","known","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("lay","laid","laid","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("lead","led","led","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("lean","leant","leant","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("leap","leapt","leapt","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("learn","learnt","learnt","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("leave","left","left","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("lend","lent","lent","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("let","let","let","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("lie","lay","lain","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("light","lit","lit","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("like","liked","liked","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("live","lived","lived","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("look","looked","looked","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("lose","lost","lost","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("make","made","made","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("mean","meant","meant","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("meet","met","met","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("melt","melted","molten","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("mislead","misled","misled","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("mistake","mistook","mistaken","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("misunderstand","misunderstood","misunderstood","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("move","moved","moved","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("mow","mowed","mown","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("need","needed","needed","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("overdraw","overdrew","overdrawn","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("overhear","overheard","overheard","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("overtake","overtook","overtaken","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("pay","paid","paid","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("play","played","played","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("preset","preset","preset","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("prove","proved","proven","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("put","put","put","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("quit","quit","quit","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("read","read","read","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("rid","rid","rid","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("ride","rode","ridden","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("ring","rang","rung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("rise","rose","risen","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("run","ran","run","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("saw","sawed","sawn","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("say","said","said","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("see","saw","seen","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("seem","seemed","seemed","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("seek","sought","sought","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sell","sold","sold","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("send","sent","sent","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("set","set","set","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sew","sewed","sewn","Join, fasten, or repair (something) by making stitches with a needle and thread"));
verbBucket.push(new Verb("shake","shook","shaken","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("shave","shaved","shaven","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("shine","shone","shone","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("shoot","shot","shot","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("show","showed","shown","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("shrink","shrank","shrunk","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("shut","shut","shut","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sing","sang","sung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sink","sank","sunk","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sit","sat","sat","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("slay","slew","slain","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sleep","slept","slept","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("slide","slid","slid","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sling","slung","slung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("slit","slit","slit","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("smell","smelt","smelt","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sneak","sneaked","sneaked","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sow","sowed","sown","Plant (seed) by scattering it on or in the earth"));
verbBucket.push(new Verb("speak","spoke","spoken","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("speed","sped","sped","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("spell","spelt","spelt","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("spend","spent","spent","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("spill","spilt","spilt","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("spin","span","spun","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("spit","spat","spat","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("split","split","split","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("spoil","spoilt","spoilt","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("spread","spread","spread","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("spring","sprang","sprung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("stand","stood","stood","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("star","started","started","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("steal","stole","stolen","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("stick","stuck","stuck","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sting","stung","stung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("stink","stank","stunk","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("strike","struck","struck","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("string","strung","strung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("strip","stript","stript","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("strive","strove","striven","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("swear","swore","sworn","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sweat","sweat","sweat","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("sweep","swept","swept","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("swell","swelled","swollen","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("swim","swam","swum","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("swing","swung","swung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("take","took","taken","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("talk","talked","talked","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("teach","taught","taught","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("tear","tore","torn","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("tell","told","told","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("think","thought","thought","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("throw","threw","thrown","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("thrust","thrust","thrust","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("tread","trod","trodden","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("try","tried","tried","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("turn","turned","turned","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("understand","understood","understood","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("upset","upset","upset","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("use","used","used","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("wake","woke","woken","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("want","wanted","wanted","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("wear","wore","worn","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("weep","wept","wept","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("wet","wet","wet","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("win","won","won","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("wind","wound","wound","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("withdraw","withdrew","withdrawn","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("withhold","withheld","withheld","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("withstand","withstood","withstood","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("work","worked","worked","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("wring","wrung","wrung","Sorry. Definition not set. Wait for the next release."));
verbBucket.push(new Verb("write","wrote","written","Sorry. Definition not set. Wait for the next release."));