
function Verb(infinitive, simple, participle, meaning)
{
	this.infinitive = infinitive;
	this.simple = simple;
	this.participle = participle;
	this.meaning = meaning;
}

function Round(min, max)
{
	this.roundVector = new Array();

	//max+1 because slice doesn't get the last index
	this.roundVector = verbBucket.slice(min, max+1);
}

verbBucket = new Array();

verbBucket.push(new Verb("ask","asked","asked","Say something in order to obtain an answer or some information"));
verbBucket.push(new Verb("awake","awoke","awoken","Stop sleeping"));
verbBucket.push(new Verb("be","was/were","been","Exist"));
verbBucket.push(new Verb("bear","bore","born","Carry/Support/Endure"));
verbBucket.push(new Verb("beat","beat","beaten","Strike/Defeat"));
verbBucket.push(new Verb("become","became","become","Begin to be"));
verbBucket.push(new Verb("begin","began","begun","Start"));
verbBucket.push(new Verb("believe","believed","believed","Accept (something) as true/Feel sure of the truth of"));
verbBucket.push(new Verb("bend","bent","bent","Shape or force (something straight) into a curve or angle/(of a person) incline the body downward from the vertical"));
verbBucket.push(new Verb("bet","bet","bet","Risk something, usually a sum of money, against someone else's on the basis of the outcome of a future event, such as the result of a race or game/Feel sure"));
verbBucket.push(new Verb("bid","bid","bid","Offer (a certain price) for something, especially at an auction"));
verbBucket.push(new Verb("bind","bound","bound","Tie or fasten (something) tightly/Cohere or cause to cohere in a single mass"));
verbBucket.push(new Verb("bite","bit","bitten","(of a person or animal) use the teeth to cut into something in order to eat it/(of a tool, tire, boot, etc.) grip a surface"));
verbBucket.push(new Verb("bleed","bled","bled","Lose blood from the body as a result of injury or illness"));
verbBucket.push(new Verb("blow","blew","blown","(of wind) move creating an air current/(of a person) expel air through pursed lips"));
verbBucket.push(new Verb("break","broke","broken","separate or cause to separate into pieces as a result of a blow, shock, or strain/interrupt (a continuity, sequence, or course)"));
verbBucket.push(new Verb("breed","bred","bred","Cause (an animal) to produce offspring, typically in a controlled and organized way"));
verbBucket.push(new Verb("bring","brought","brought","Come to a place with (someone or something)/cause (someone or something) to come to a place/make (someone or something) move in a particular direction or way"));
verbBucket.push(new Verb("broadcast","broadcast","broadcast","Transmit (a program or some information) by radio or television/scatter (seeds) by hand or machine rather than placing in drills or rows"));
verbBucket.push(new Verb("build","built","built","Construct (something, typically something large) by putting parts or material together over a period of time"));
verbBucket.push(new Verb("burn","burnt","burnt","(of a fire) flame or glow while consuming a material such as coal or wood/(of a person, the skin, or a part of the body) become red and painful through exposure to the sun"));
verbBucket.push(new Verb("burst","burst","burst","(of a container) break suddenly and violently apart, spilling the contents, typically as a result of an impact or internal pressure"));
verbBucket.push(new Verb("bust","bust","bust","To go bankrupt/to collapse from the strain of making a supreme effort"));
verbBucket.push(new Verb("buy","bought","bought","Obtain in exchange for payment"));
verbBucket.push(new Verb("call","called","called","Cry out to (someone) in order to summon them or attract their attention/Give (an infant or animal) a specified name"));
verbBucket.push(new Verb("cast","cast","cast","Throw (something) forcefully in a specified direction/Cause (light or shadow) to appear on a surface"));
verbBucket.push(new Verb("catch","caught","caught","Intercept and hold (something that has been thrown, propelled, or dropped)/Capture (a person or animal that tries or would try to escape)"));
verbBucket.push(new Verb("choose","chose","chosen","Pick out or select (someone or something) as being the best or most appropriate of two or more alternatives"));
verbBucket.push(new Verb("clap","clapped","clapped","Strike the palms of (one's hands) together repeatedly, typically in order to applaud"));
verbBucket.push(new Verb("cling","clung","clung","(of a person or animal) hold on tightly to"));
verbBucket.push(new Verb("come","came","come","Move or travel toward or into a place thought of as near or familiar to the speaker/Occur; happen; take place"));
verbBucket.push(new Verb("cost","cost","cost","(of an object or an action) require the payment of (a specified sum of money) before it can be acquired or done/Estimate the price of"));
verbBucket.push(new Verb("creep","crept","crept","Move slowly and carefully, especially in order to avoid being heard or noticed/(of an unwanted and negative characteristic or fact) occur or develop gradually and almost imperceptibly"));
verbBucket.push(new Verb("cut","cut","cut","Make an opening, incision, or wound in (something) with a sharp-edged tool or object/Remove (something) from something larger by using a sharp implement"));
verbBucket.push(new Verb("dare","dared","dared","Not implemented exception."));
verbBucket.push(new Verb("deal","dealt","dealt","Not implemented exception."));
verbBucket.push(new Verb("dig","dug","dug","Not implemented exception."));
verbBucket.push(new Verb("dive","dived","dived","Not implemented exception."));
verbBucket.push(new Verb("do","did","done","Not implemented exception."));
verbBucket.push(new Verb("draw","drew","drawn","Not implemented exception."));
verbBucket.push(new Verb("dream","dreamt","dreamt","Not implemented exception."));
verbBucket.push(new Verb("drink","drank","drunk","Not implemented exception."));
verbBucket.push(new Verb("drive","drove","driven","Not implemented exception."));
verbBucket.push(new Verb("eat","ate","eaten","Not implemented exception."));
verbBucket.push(new Verb("fall","fell","fallen","Not implemented exception."));
verbBucket.push(new Verb("feed","fed","fed","Not implemented exception."));
verbBucket.push(new Verb("feel","felt","felt","Not implemented exception."));
verbBucket.push(new Verb("fight","fought","fought","Not implemented exception."));
verbBucket.push(new Verb("find","found","found","Not implemented exception."));
verbBucket.push(new Verb("fit","fit","fit","Not implemented exception."));
verbBucket.push(new Verb("flee","fled","fled","Not implemented exception."));
verbBucket.push(new Verb("fling","flung","flung","Not implemented exception."));
verbBucket.push(new Verb("fly","flew","flown","Not implemented exception."));
verbBucket.push(new Verb("forbid","forbade","forbidden","Not implemented exception."));
verbBucket.push(new Verb("forecast","forecast","forecast","Not implemented exception."));
verbBucket.push(new Verb("foresee","foresaw","foreseen","Not implemented exception."));
verbBucket.push(new Verb("forget","forgot","forgotten","Not implemented exception."));
verbBucket.push(new Verb("forgive","forgave","forgiven","Not implemented exception."));
verbBucket.push(new Verb("forsake","forsook","forsaken","Not implemented exception."));
verbBucket.push(new Verb("freeze","froze","frozen","Not implemented exception."));
verbBucket.push(new Verb("get","got","got","Not implemented exception."));
verbBucket.push(new Verb("give","gave","given","Not implemented exception."));
verbBucket.push(new Verb("go","went","gone/been","Not implemented exception."));
verbBucket.push(new Verb("grind","ground","ground","Not implemented exception."));
verbBucket.push(new Verb("grow","grew","grown","Not implemented exception."));
verbBucket.push(new Verb("handwrite","handwrote","handwritten","Not implemented exception."));
verbBucket.push(new Verb("hang","hung","hung","Not implemented exception."));
verbBucket.push(new Verb("have","had","had","Not implemented exception."));
verbBucket.push(new Verb("hear","heard","heard","Not implemented exception."));
verbBucket.push(new Verb("help","helped","helped","Not implemented exception."));
verbBucket.push(new Verb("hide","hid","hidden","Not implemented exception."));
verbBucket.push(new Verb("hit","hit","hit","Not implemented exception."));
verbBucket.push(new Verb("hold","held","held","Not implemented exception."));
verbBucket.push(new Verb("hurt","hurt","hurt","Not implemented exception."));
verbBucket.push(new Verb("inlay","inlaid","inlaid","Not implemented exception."));
verbBucket.push(new Verb("input","input","input","Not implemented exception."));
verbBucket.push(new Verb("keep","kept","kept","Not implemented exception."));
verbBucket.push(new Verb("kneel","knelt","knelt","Not implemented exception."));
verbBucket.push(new Verb("knit","knit","knit","Not implemented exception."));
verbBucket.push(new Verb("know","knew","known","Not implemented exception."));
verbBucket.push(new Verb("lay","laid","laid","Not implemented exception."));
verbBucket.push(new Verb("lead","led","led","Not implemented exception."));
verbBucket.push(new Verb("lean","leant","leant","Not implemented exception."));
verbBucket.push(new Verb("leap","leapt","leapt","Not implemented exception."));
verbBucket.push(new Verb("learn","learnt","learnt","Not implemented exception."));
verbBucket.push(new Verb("leave","left","left","Not implemented exception."));
verbBucket.push(new Verb("lend","lent","lent","Not implemented exception."));
verbBucket.push(new Verb("let","let","let","Not implemented exception."));
verbBucket.push(new Verb("lie","lay","lain","Not implemented exception."));
verbBucket.push(new Verb("light","lit","lit","Not implemented exception."));
verbBucket.push(new Verb("like","liked","liked","Not implemented exception."));
verbBucket.push(new Verb("live","lived","lived","Not implemented exception."));
verbBucket.push(new Verb("look","looked","looked","Not implemented exception."));
verbBucket.push(new Verb("lose","lost","lost","Not implemented exception."));
verbBucket.push(new Verb("make","made","made","Not implemented exception."));
verbBucket.push(new Verb("mean","meant","meant","Not implemented exception."));
verbBucket.push(new Verb("meet","met","met","Not implemented exception."));
verbBucket.push(new Verb("melt","melted","molten","Not implemented exception."));
verbBucket.push(new Verb("mislead","misled","misled","Not implemented exception."));
verbBucket.push(new Verb("mistake","mistook","mistaken","Not implemented exception."));
verbBucket.push(new Verb("misunderstand","misunderstood","misunderstood","Not implemented exception."));
verbBucket.push(new Verb("move","moved","moved","Not implemented exception."));
verbBucket.push(new Verb("mow","mowed","mown","Not implemented exception."));
verbBucket.push(new Verb("need","needed","needed","Not implemented exception."));
verbBucket.push(new Verb("overdraw","overdrew","overdrawn","Not implemented exception."));
verbBucket.push(new Verb("overhear","overheard","overheard","Not implemented exception."));
verbBucket.push(new Verb("overtake","overtook","overtaken","Not implemented exception."));
verbBucket.push(new Verb("pay","paid","paid","Not implemented exception."));
verbBucket.push(new Verb("play","played","played","Not implemented exception."));
verbBucket.push(new Verb("preset","preset","preset","Not implemented exception."));
verbBucket.push(new Verb("prove","proved","proven","Not implemented exception."));
verbBucket.push(new Verb("put","put","put","Not implemented exception."));
verbBucket.push(new Verb("quit","quit","quit","Not implemented exception."));
verbBucket.push(new Verb("read","read","read","Not implemented exception."));
verbBucket.push(new Verb("rid","rid","rid","Not implemented exception."));
verbBucket.push(new Verb("ride","rode","ridden","Not implemented exception."));
verbBucket.push(new Verb("ring","rang","rung","Not implemented exception."));
verbBucket.push(new Verb("rise","rose","risen","Not implemented exception."));
verbBucket.push(new Verb("run","ran","run","Not implemented exception."));
verbBucket.push(new Verb("saw","sawed","sawn","Not implemented exception."));
verbBucket.push(new Verb("say","said","said","Not implemented exception."));
verbBucket.push(new Verb("see","saw","seen","Not implemented exception."));
verbBucket.push(new Verb("seem","seemed","seemed","Not implemented exception."));
verbBucket.push(new Verb("seek","sought","sought","Not implemented exception."));
verbBucket.push(new Verb("sell","sold","sold","Not implemented exception."));
verbBucket.push(new Verb("send","sent","sent","Not implemented exception."));
verbBucket.push(new Verb("set","set","set","Not implemented exception."));
verbBucket.push(new Verb("sew","sewed","sewn","Join, fasten, or repair (something) by making stitches with a needle and thread"));
verbBucket.push(new Verb("shake","shook","shaken","Not implemented exception."));
verbBucket.push(new Verb("shave","shaved","shaven","Not implemented exception."));
verbBucket.push(new Verb("shine","shone","shone","Not implemented exception."));
verbBucket.push(new Verb("shoot","shot","shot","Not implemented exception."));
verbBucket.push(new Verb("show","showed","shown","Not implemented exception."));
verbBucket.push(new Verb("shrink","shrank","shrunk","Not implemented exception."));
verbBucket.push(new Verb("shut","shut","shut","Not implemented exception."));
verbBucket.push(new Verb("sing","sang","sung","Not implemented exception."));
verbBucket.push(new Verb("sink","sank","sunk","Not implemented exception."));
verbBucket.push(new Verb("sit","sat","sat","Not implemented exception."));
verbBucket.push(new Verb("slay","slew","slain","Not implemented exception."));
verbBucket.push(new Verb("sleep","slept","slept","Not implemented exception."));
verbBucket.push(new Verb("slide","slid","slid","Not implemented exception."));
verbBucket.push(new Verb("sling","slung","slung","Not implemented exception."));
verbBucket.push(new Verb("slit","slit","slit","Not implemented exception."));
verbBucket.push(new Verb("smell","smelt","smelt","Not implemented exception."));
verbBucket.push(new Verb("sneak","sneaked","sneaked","Not implemented exception."));
verbBucket.push(new Verb("sow","sowed","sown","Plant (seed) by scattering it on or in the earth"));
verbBucket.push(new Verb("speak","spoke","spoken","Not implemented exception."));
verbBucket.push(new Verb("speed","sped","sped","Not implemented exception."));
verbBucket.push(new Verb("spell","spelt","spelt","Not implemented exception."));
verbBucket.push(new Verb("spend","spent","spent","Not implemented exception."));
verbBucket.push(new Verb("spill","spilt","spilt","Not implemented exception."));
verbBucket.push(new Verb("spin","span","spun","Not implemented exception."));
verbBucket.push(new Verb("spit","spat","spat","Not implemented exception."));
verbBucket.push(new Verb("split","split","split","Not implemented exception."));
verbBucket.push(new Verb("spoil","spoilt","spoilt","Not implemented exception."));
verbBucket.push(new Verb("spread","spread","spread","Not implemented exception."));
verbBucket.push(new Verb("spring","sprang","sprung","Not implemented exception."));
verbBucket.push(new Verb("stand","stood","stood","Not implemented exception."));
verbBucket.push(new Verb("star","started","started","Not implemented exception."));
verbBucket.push(new Verb("steal","stole","stolen","Not implemented exception."));
verbBucket.push(new Verb("stick","stuck","stuck","Not implemented exception."));
verbBucket.push(new Verb("sting","stung","stung","Not implemented exception."));
verbBucket.push(new Verb("stink","stank","stunk","Not implemented exception."));
verbBucket.push(new Verb("strike","struck","struck","Not implemented exception."));
verbBucket.push(new Verb("string","strung","strung","Not implemented exception."));
verbBucket.push(new Verb("strip","stript","stript","Not implemented exception."));
verbBucket.push(new Verb("strive","strove","striven","Not implemented exception."));
verbBucket.push(new Verb("swear","swore","sworn","Not implemented exception."));
verbBucket.push(new Verb("sweat","sweat","sweat","Not implemented exception."));
verbBucket.push(new Verb("sweep","swept","swept","Not implemented exception."));
verbBucket.push(new Verb("swell","swelled","swollen","Not implemented exception."));
verbBucket.push(new Verb("swim","swam","swum","Not implemented exception."));
verbBucket.push(new Verb("swing","swung","swung","Not implemented exception."));
verbBucket.push(new Verb("take","took","taken","Not implemented exception."));
verbBucket.push(new Verb("talk","talked","talked","Not implemented exception."));
verbBucket.push(new Verb("teach","taught","taught","Not implemented exception."));
verbBucket.push(new Verb("tear","tore","torn","Not implemented exception."));
verbBucket.push(new Verb("tell","told","told","Not implemented exception."));
verbBucket.push(new Verb("think","thought","thought","Not implemented exception."));
verbBucket.push(new Verb("throw","threw","thrown","Not implemented exception."));
verbBucket.push(new Verb("thrust","thrust","thrust","Not implemented exception."));
verbBucket.push(new Verb("tread","trod","trodden","Not implemented exception."));
verbBucket.push(new Verb("try","tried","tried","Not implemented exception."));
verbBucket.push(new Verb("turn","turned","turned","Not implemented exception."));
verbBucket.push(new Verb("understand","understood","understood","Not implemented exception."));
verbBucket.push(new Verb("upset","upset","upset","Not implemented exception."));
verbBucket.push(new Verb("use","used","used","Not implemented exception."));
verbBucket.push(new Verb("wake","woke","woken","Not implemented exception."));
verbBucket.push(new Verb("want","wanted","wanted","Not implemented exception."));
verbBucket.push(new Verb("wear","wore","worn","Not implemented exception."));
verbBucket.push(new Verb("weep","wept","wept","Not implemented exception."));
verbBucket.push(new Verb("wet","wet","wet","Not implemented exception."));
verbBucket.push(new Verb("win","won","won","Not implemented exception."));
verbBucket.push(new Verb("wind","wound","wound","Not implemented exception."));
verbBucket.push(new Verb("withdraw","withdrew","withdrawn","Not implemented exception."));
verbBucket.push(new Verb("withhold","withheld","withheld","Not implemented exception."));
verbBucket.push(new Verb("withstand","withstood","withstood","Not implemented exception."));
verbBucket.push(new Verb("work","worked","worked","Not implemented exception."));
verbBucket.push(new Verb("wring","wrung","wrung","Not implemented exception."));
verbBucket.push(new Verb("write","wrote","written","Not implemented exception."));